---
- name: add certbot ppa
  apt_repository:
    repo: ppa:certbot/certbot

- name: install packages
  apt:
    name: "{{ packages }}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - certbot

- name: delete default cronjob
  file:
    state: absent
    path: /etc/cron.d/certbot

- name: create /etc/letsencrypt/ini directory
  file:
    state: directory
    path: /etc/letsencrypt/ini

- name: include apache webroot config
  include: apache.yml
  when: letsencrypt_authenticator == 'webroot' and letsencrypt_webserver == 'apache'

- name: include nginx webroot config
  include: nginx.yml
  when: letsencrypt_authenticator == 'webroot' and letsencrypt_webserver == 'nginx'

- name: run pre hook
  command: "{{ letsencrypt_prehook }}"
  when: letsencrypt_prehook is defined
  ignore_errors: True

- name: use standalone authenticator
  include: standalone.yml
  with_items: "{{ letsencrypt_inis }}"
  when: letsencrypt_authenticator == 'standalone'
  loop_control:
    loop_var: ini

- name: use webroot authenticator
  include: webroot.yml
  with_items: "{{ letsencrypt_inis }}"
  when: letsencrypt_authenticator == 'webroot'
  loop_control:
    loop_var: ini

- name: run post hook
  command: "{{ letsencrypt_posthook }}"
  when: letsencrypt_posthook is defined
  ignore_errors: True

- name: set prehook string
  set_fact:
    _prehook: "{{ letsencrypt_prehook }}; "
  when: letsencrypt_prehook is defined

- name: set prehook empty string
  set_fact:
    _prehook: ''
  when: letsencrypt_prehook is not defined

- name: set posthook string
  set_fact:
    _posthook: "; {{ letsencrypt_posthook }}"
  when: letsencrypt_posthook is defined

- name: set posthook empty string
  set_fact:
    _posthook: ''
  when: letsencrypt_posthook is not defined

- name: create renew cron job
  cron:
    name: letsencrypt_renew
    month: "*"
    day: "1"
    hour: "2"
    minute: "0"
    user: root
    job: '{{ _prehook }}certbot renew -n{{ _posthook }}'

...
